"""add phone number

Revision ID: 8bb6f9149626
Revises: 8da99f4615d5
Create Date: 2022-02-10 10:50:07.935321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb6f9149626'
down_revision = '8da99f4615d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_numer')
    # ### end Alembic commands ###
